"""
Run with: python seed.py
Populates 25 yoga poses (bilingual, with real working images) and sample videos.

NOTE ON IMAGES: these use real, working Unsplash photos of general yoga/stretching
scenes (free to use). They are representative, not exact photos of each specific
pose — Unsplash doesn't have a verified photo for every named asana. Swap in
pose-specific photography later if you want exact visual matches; for now these
guarantee something actually renders instead of a broken image icon.
"""
from app.database import poses_collection, videos_collection

# A rotating set of real, working Unsplash yoga/stretching photos
IMAGES = [
    "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&q=80",
    "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&q=80",
    "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&q=80",
    "https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=600&q=80",
    "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80",
    "https://images.unsplash.com/photo-1588286840104-8957b019727f?w=600&q=80",
    "https://images.unsplash.com/photo-1552196563-55cd4e45efb3?w=600&q=80",
    "https://images.unsplash.com/photo-1506126613408-4e0efab08cae?w=600&q=80",
    "https://images.unsplash.com/photo-1591228127791-8e2eaef098d3?w=600&q=80",
    "https://images.unsplash.com/photo-1600881333168-2ef49b341f30?w=600&q=80",
]

def img(i):
    return IMAGES[i % len(IMAGES)]

poses = [
    {
        "name_en": "Tadasana (Mountain Pose)", "name_hi": "ताड़ासन",
        "image_url": img(0),
        "benefits_en": "Improves posture, balance, and body awareness; the foundation for all standing poses.",
        "benefits_hi": "मुद्रा, संतुलन और शरीर की जागरूकता में सुधार करता है; सभी खड़े आसनों की नींव।",
        "steps_en": ["Stand with feet together, weight evenly distributed", "Engage thighs, lengthen spine", "Arms relaxed at sides, palms facing forward", "Breathe steadily for 30-60 seconds"],
        "steps_hi": ["पैरों को साथ रखकर खड़े हों, वजन समान रूप से बांटें", "जांघों को कस लें, रीढ़ को लंबा करें", "हाथ बगल में आराम से, हथेलियां आगे", "30-60 सेकंड सांस लें"],
        "precautions_en": "Generally safe for all levels.",
        "precautions_hi": "सभी स्तरों के लिए सुरक्षित।",
        "related_conditions": ["balance", "stress"],
    },
    {
        "name_en": "Vrikshasana (Tree Pose)", "name_hi": "वृक्षासन",
        "image_url": img(1),
        "benefits_en": "Improves balance and focus, strengthens legs, calms the mind.",
        "benefits_hi": "संतुलन और एकाग्रता में सुधार, पैरों को मजबूत करता है, मन को शांत करता है।",
        "steps_en": ["Stand tall", "Place one foot on the inner thigh", "Bring hands to heart center", "Hold and breathe"],
        "steps_hi": ["सीधे खड़े हों", "एक पैर को दूसरी जांघ पर रखें", "हाथों को हृदय के पास लाएं", "रुकें और सांस लें"],
        "precautions_en": "Avoid if you have severe balance issues or knee injuries.",
        "precautions_hi": "गंभीर संतुलन समस्या या घुटने की चोट होने पर न करें।",
        "related_conditions": ["stress", "balance"],
    },
    {
        "name_en": "Trikonasana (Triangle Pose)", "name_hi": "त्रिकोणासन",
        "image_url": img(2),
        "benefits_en": "Stretches legs, hips, and spine; improves digestion and reduces stress.",
        "benefits_hi": "पैरों, कूल्हों और रीढ़ को खींचता है; पाचन में सुधार करता है और तनाव कम करता है।",
        "steps_en": ["Stand with feet wide apart", "Extend arms parallel to floor", "Reach one hand down to shin/floor, other hand up", "Hold, then switch sides"],
        "steps_hi": ["पैरों को चौड़ा करके खड़े हों", "हाथों को फर्श के समानांतर फैलाएं", "एक हाथ नीचे पिंडली/फर्श तक, दूसरा ऊपर", "रुकें, फिर पक्ष बदलें"],
        "precautions_en": "Avoid with severe back or neck injury.",
        "precautions_hi": "गंभीर पीठ या गर्दन की चोट होने पर न करें।",
        "related_conditions": ["diabetes", "stress"],
    },
    {
        "name_en": "Adho Mukha Svanasana (Downward Dog)", "name_hi": "अधोमुख श्वानासन",
        "image_url": img(3),
        "benefits_en": "Stretches the whole body, improves circulation, energizes and calms simultaneously.",
        "benefits_hi": "पूरे शरीर को खींचता है, रक्त संचार सुधारता है, ऊर्जा देता है और शांत करता है।",
        "steps_en": ["Start on hands and knees", "Lift hips up and back, forming an inverted V", "Press heels toward floor, lengthen spine", "Hold for 5-10 breaths"],
        "steps_hi": ["हाथों और घुटनों पर शुरू करें", "कूल्हों को ऊपर और पीछे उठाएं, उल्टा V बनाएं", "एड़ियों को फर्श की ओर दबाएं, रीढ़ लंबी करें", "5-10 सांसों तक रुकें"],
        "precautions_en": "Avoid with carpal tunnel syndrome or high blood pressure without guidance.",
        "precautions_hi": "कार्पल टनल सिंड्रोम या उच्च रक्तचाप में मार्गदर्शन के बिना न करें।",
        "related_conditions": ["heart", "stress"],
    },
    {
        "name_en": "Bhujangasana (Cobra Pose)", "name_hi": "भुजंगासन",
        "image_url": img(4),
        "benefits_en": "Strengthens the spine, opens the chest and lungs, improves circulation to the heart.",
        "benefits_hi": "रीढ़ को मजबूत करता है, छाती और फेफड़े खोलता है, हृदय को रक्त संचार बेहतर करता है।",
        "steps_en": ["Lie on stomach, hands under shoulders", "Press into hands, lift chest up", "Keep elbows slightly bent", "Hold for 15-30 seconds"],
        "steps_hi": ["पेट के बल लेटें, हाथ कंधों के नीचे", "हाथों पर दबाव डालें, छाती ऊपर उठाएं", "कोहनी थोड़ी मुड़ी रखें", "15-30 सेकंड रुकें"],
        "precautions_en": "Avoid with back injury or pregnancy.",
        "precautions_hi": "पीठ की चोट या गर्भावस्था में न करें।",
        "related_conditions": ["heart"],
    },
    {
        "name_en": "Setu Bandhasana (Bridge Pose)", "name_hi": "सेतु बंधासन",
        "image_url": img(5),
        "benefits_en": "Strengthens the heart, improves circulation, reduces anxiety.",
        "benefits_hi": "हृदय को मजबूत करता है, रक्त संचार सुधारता है, चिंता कम करता है।",
        "steps_en": ["Lie on your back, knees bent", "Lift hips upward", "Clasp hands beneath you", "Hold and release slowly"],
        "steps_hi": ["पीठ के बल लेटें, घुटने मोड़ें", "कूल्हों को ऊपर उठाएं", "हाथों को नीचे मिलाएं", "रुकें और धीरे से छोड़ें"],
        "precautions_en": "Avoid with neck or back injuries.",
        "precautions_hi": "गर्दन या पीठ की चोट होने पर न करें।",
        "related_conditions": ["heart", "stress"],
    },
    {
        "name_en": "Balasana (Child's Pose)", "name_hi": "बालासन",
        "image_url": img(6),
        "benefits_en": "Gently stretches hips and back, calms the nervous system, relieves stress.",
        "benefits_hi": "कूल्हों और पीठ को धीरे से खींचता है, तंत्रिका तंत्र को शांत करता है, तनाव दूर करता है।",
        "steps_en": ["Kneel and sit back on heels", "Fold forward, arms extended", "Rest forehead on the floor", "Breathe deeply for 1-2 minutes"],
        "steps_hi": ["घुटनों के बल बैठें, एड़ियों पर बैठें", "आगे झुकें, हाथ फैलाएं", "माथे को फर्श पर रखें", "1-2 मिनट गहरी सांस लें"],
        "precautions_en": "Avoid with knee injuries.",
        "precautions_hi": "घुटने की चोट होने पर न करें।",
        "related_conditions": ["stress"],
    },
    {
        "name_en": "Paschimottanasana (Seated Forward Bend)", "name_hi": "पश्चिमोत्तानासन",
        "image_url": img(7),
        "benefits_en": "Stretches the spine and hamstrings, calms the mind, aids digestion.",
        "benefits_hi": "रीढ़ और हैमस्ट्रिंग को खींचता है, मन को शांत करता है, पाचन में मदद करता है।",
        "steps_en": ["Sit with legs extended forward", "Inhale, lengthen spine", "Exhale, fold forward reaching for feet", "Hold for 30-60 seconds"],
        "steps_hi": ["पैर आगे फैलाकर बैठें", "सांस लें, रीढ़ लंबी करें", "सांस छोड़ें, आगे झुककर पैरों तक पहुंचें", "30-60 सेकंड रुकें"],
        "precautions_en": "Avoid with lower back injury.",
        "precautions_hi": "पीठ के निचले हिस्से की चोट में न करें।",
        "related_conditions": ["diabetes", "stress"],
    },
    {
        "name_en": "Ardha Matsyendrasana (Half Spinal Twist)", "name_hi": "अर्ध मत्स्येन्द्रासन",
        "image_url": img(8),
        "benefits_en": "Improves spinal flexibility, stimulates digestion, detoxifies internal organs.",
        "benefits_hi": "रीढ़ की लचक सुधारता है, पाचन को उत्तेजित करता है, आंतरिक अंगों को detox करता है।",
        "steps_en": ["Sit with legs extended", "Bend one knee, cross it over", "Twist torso toward bent knee", "Hold, then switch sides"],
        "steps_hi": ["पैर फैलाकर बैठें", "एक घुटना मोड़ें, उसे पार करें", "मुड़े घुटने की ओर धड़ मोड़ें", "रुकें, फिर पक्ष बदलें"],
        "precautions_en": "Avoid with spinal injury or during pregnancy.",
        "precautions_hi": "रीढ़ की चोट या गर्भावस्था में न करें।",
        "related_conditions": ["diabetes"],
    },
    {
        "name_en": "Virabhadrasana I (Warrior I)", "name_hi": "वीरभद्रासन I",
        "image_url": img(9),
        "benefits_en": "Builds strength in legs and core, opens hips and chest, boosts stamina.",
        "benefits_hi": "पैरों और कोर में ताकत बनाता है, कूल्हे और छाती खोलता है, सहनशक्ति बढ़ाता है।",
        "steps_en": ["Step one foot back, bend front knee", "Square hips forward", "Raise arms overhead", "Hold, then switch sides"],
        "steps_hi": ["एक पैर पीछे रखें, अगला घुटना मोड़ें", "कूल्हों को आगे रखें", "हाथ ऊपर उठाएं", "रुकें, फिर पक्ष बदलें"],
        "precautions_en": "Avoid with knee or hip injuries.",
        "precautions_hi": "घुटने या कूल्हे की चोट में न करें।",
        "related_conditions": ["diabetes", "hypertension"],
    },
    {
        "name_en": "Virabhadrasana II (Warrior II)", "name_hi": "वीरभद्रासन II",
        "image_url": img(0),
        "benefits_en": "Strengthens legs, opens hips, improves stamina and concentration.",
        "benefits_hi": "पैरों को मजबूत करता है, कूल्हे खोलता है, सहनशक्ति और एकाग्रता सुधारता है।",
        "steps_en": ["Step feet wide apart, turn one foot out", "Bend front knee to 90 degrees", "Extend arms parallel to floor", "Gaze over front hand, hold"],
        "steps_hi": ["पैर चौड़े रखें, एक पैर बाहर मोड़ें", "अगला घुटना 90 डिग्री मोड़ें", "हाथ फर्श के समानांतर फैलाएं", "आगे के हाथ की ओर देखें, रुकें"],
        "precautions_en": "Avoid with knee injuries.",
        "precautions_hi": "घुटने की चोट में न करें।",
        "related_conditions": ["hypertension"],
    },
    {
        "name_en": "Utkatasana (Chair Pose)", "name_hi": "उत्कटासन",
        "image_url": img(1),
        "benefits_en": "Strengthens thighs and core, builds heat and stamina, improves balance.",
        "benefits_hi": "जांघों और कोर को मजबूत करता है, गर्मी और सहनशक्ति बनाता है, संतुलन सुधारता है।",
        "steps_en": ["Stand with feet together", "Bend knees as if sitting in a chair", "Raise arms overhead", "Hold for 20-30 seconds"],
        "steps_hi": ["पैर साथ रखकर खड़े हों", "घुटने मोड़ें जैसे कुर्सी पर बैठ रहे हों", "हाथ ऊपर उठाएं", "20-30 सेकंड रुकें"],
        "precautions_en": "Avoid with knee injuries or low blood pressure.",
        "precautions_hi": "घुटने की चोट या निम्न रक्तचाप में न करें।",
        "related_conditions": ["diabetes"],
    },
    {
        "name_en": "Marjaryasana-Bitilasana (Cat-Cow Pose)", "name_hi": "मार्जरी-बितिलासन",
        "image_url": img(2),
        "benefits_en": "Improves spinal flexibility, relieves back tension, coordinates breath with movement.",
        "benefits_hi": "रीढ़ की लचक सुधारता है, पीठ का तनाव कम करता है, सांस और गति को समन्वित करता है।",
        "steps_en": ["Start on hands and knees", "Inhale, arch back, look up (Cow)", "Exhale, round spine, tuck chin (Cat)", "Repeat 10-15 times"],
        "steps_hi": ["हाथों और घुटनों पर शुरू करें", "सांस लें, पीठ मोड़ें, ऊपर देखें (गाय)", "सांस छोड़ें, रीढ़ गोल करें, ठुड्डी अंदर करें (बिल्ली)", "10-15 बार दोहराएं"],
        "precautions_en": "Generally safe for all levels.",
        "precautions_hi": "सभी स्तरों के लिए सुरक्षित।",
        "related_conditions": ["stress", "balance"],
    },
    {
        "name_en": "Sukhasana (Easy Pose)", "name_hi": "सुखासन",
        "image_url": img(3),
        "benefits_en": "Calms the mind, improves posture, ideal for meditation and breathing exercises.",
        "benefits_hi": "मन को शांत करता है, मुद्रा सुधारता है, ध्यान और श्वास अभ्यास के लिए आदर्श।",
        "steps_en": ["Sit cross-legged on the floor", "Lengthen the spine", "Rest hands on knees", "Close eyes, breathe deeply"],
        "steps_hi": ["फर्श पर पालथी मारकर बैठें", "रीढ़ लंबी करें", "हाथ घुटनों पर रखें", "आंखें बंद करें, गहरी सांस लें"],
        "precautions_en": "Use a cushion under hips if uncomfortable.",
        "precautions_hi": "असुविधा होने पर कूल्हों के नीचे तकिया रखें।",
        "related_conditions": ["stress"],
    },
    {
        "name_en": "Dhanurasana (Bow Pose)", "name_hi": "धनुरासन",
        "image_url": img(4),
        "benefits_en": "Strengthens back muscles, opens chest, stimulates digestive organs.",
        "benefits_hi": "पीठ की मांसपेशियों को मजबूत करता है, छाती खोलता है, पाचन अंगों को उत्तेजित करता है।",
        "steps_en": ["Lie on stomach", "Bend knees, hold ankles", "Lift chest and thighs off floor", "Hold for 15-20 seconds"],
        "steps_hi": ["पेट के बल लेटें", "घुटने मोड़ें, टखने पकड़ें", "छाती और जांघों को फर्श से उठाएं", "15-20 सेकंड रुकें"],
        "precautions_en": "Avoid with back or neck injury, high blood pressure.",
        "precautions_hi": "पीठ या गर्दन की चोट, उच्च रक्तचाप में न करें।",
        "related_conditions": ["diabetes"],
    },
    {
        "name_en": "Naukasana (Boat Pose)", "name_hi": "नौकासन",
        "image_url": img(5),
        "benefits_en": "Strengthens core and hip flexors, improves balance and digestion.",
        "benefits_hi": "कोर और कूल्हे के फ्लेक्सर्स को मजबूत करता है, संतुलन और पाचन सुधारता है।",
        "steps_en": ["Sit with knees bent", "Lean back slightly, lift feet off floor", "Extend arms forward, balance on sit bones", "Hold for 15-30 seconds"],
        "steps_hi": ["घुटने मोड़कर बैठें", "थोड़ा पीछे झुकें, पैर फर्श से उठाएं", "हाथ आगे फैलाएं, सिट बोन्स पर संतुलन बनाएं", "15-30 सेकंड रुकें"],
        "precautions_en": "Avoid with lower back issues or during pregnancy.",
        "precautions_hi": "पीठ के निचले हिस्से की समस्या या गर्भावस्था में न करें।",
        "related_conditions": ["diabetes"],
    },
    {
        "name_en": "Ustrasana (Camel Pose)", "name_hi": "उष्ट्रासन",
        "image_url": img(6),
        "benefits_en": "Opens chest and shoulders, improves posture, energizes the body.",
        "benefits_hi": "छाती और कंधे खोलता है, मुद्रा सुधारता है, शरीर को ऊर्जावान बनाता है।",
        "steps_en": ["Kneel with hips over knees", "Place hands on lower back", "Arch back, reach for heels", "Hold for 15-30 seconds"],
        "steps_hi": ["घुटनों पर कूल्हे रखकर घुटने टेकें", "हाथ पीठ के निचले हिस्से पर रखें", "पीठ मोड़ें, एड़ियों तक पहुंचें", "15-30 सेकंड रुकें"],
        "precautions_en": "Avoid with neck or lower back injury.",
        "precautions_hi": "गर्दन या पीठ के निचले हिस्से की चोट में न करें।",
        "related_conditions": ["stress"],
    },
    {
        "name_en": "Halasana (Plow Pose)", "name_hi": "हलासन",
        "image_url": img(7),
        "benefits_en": "Stretches shoulders and spine, calms the nervous system, stimulates thyroid.",
        "benefits_hi": "कंधे और रीढ़ को खींचता है, तंत्रिका तंत्र को शांत करता है, थायराइड को उत्तेजित करता है।",
        "steps_en": ["Lie on back, legs raised", "Swing legs overhead, toes touching floor", "Support back with hands", "Hold for 30-60 seconds"],
        "steps_hi": ["पीठ के बल लेटें, पैर उठाएं", "पैरों को सिर के ऊपर लाएं, पैर की उंगलियां फर्श छूएं", "हाथों से पीठ को सहारा दें", "30-60 सेकंड रुकें"],
        "precautions_en": "Avoid with neck injury or high blood pressure; not for beginners without guidance.",
        "precautions_hi": "गर्दन की चोट या उच्च रक्तचाप में न करें; बिना मार्गदर्शन शुरुआती न करें।",
        "related_conditions": ["stress", "hypertension"],
    },
    {
        "name_en": "Matsyasana (Fish Pose)", "name_hi": "मत्स्यासन",
        "image_url": img(8),
        "benefits_en": "Opens chest and throat, relieves tension in neck and shoulders.",
        "benefits_hi": "छाती और गले को खोलता है, गर्दन और कंधों का तनाव दूर करता है।",
        "steps_en": ["Lie on back", "Slide hands under hips", "Lift chest, tilt head back", "Hold for 15-30 seconds"],
        "steps_hi": ["पीठ के बल लेटें", "हाथों को कूल्हों के नीचे रखें", "छाती उठाएं, सिर पीछे झुकाएं", "15-30 सेकंड रुकें"],
        "precautions_en": "Avoid with neck injury or migraine.",
        "precautions_hi": "गर्दन की चोट या माइग्रेन में न करें।",
        "related_conditions": ["stress"],
    },
    {
        "name_en": "Gomukhasana (Cow Face Pose)", "name_hi": "गोमुखासन",
        "image_url": img(9),
        "benefits_en": "Stretches shoulders, hips, and thighs; improves posture.",
        "benefits_hi": "कंधे, कूल्हे और जांघों को खींचता है; मुद्रा सुधारता है।",
        "steps_en": ["Sit with one knee stacked over the other", "Reach one arm up, one arm behind back", "Clasp hands if possible", "Hold, then switch sides"],
        "steps_hi": ["एक घुटने को दूसरे के ऊपर रखकर बैठें", "एक हाथ ऊपर, एक पीठ के पीछे", "यदि संभव हो तो हाथ जोड़ें", "रुकें, फिर पक्ष बदलें"],
        "precautions_en": "Avoid with shoulder or knee injuries.",
        "precautions_hi": "कंधे या घुटने की चोट में न करें।",
        "related_conditions": ["stress"],
    },
    {
        "name_en": "Padmasana (Lotus Pose)", "name_hi": "पद्मासन",
        "image_url": img(0),
        "benefits_en": "Deepens meditation, improves hip flexibility, calms the mind.",
        "benefits_hi": "ध्यान को गहरा करता है, कूल्हे की लचक सुधारता है, मन को शांत करता है।",
        "steps_en": ["Sit on the floor", "Place each foot on the opposite thigh", "Rest hands on knees", "Breathe steadily, hold as long as comfortable"],
        "steps_hi": ["फर्श पर बैठें", "प्रत्येक पैर को विपरीत जांघ पर रखें", "हाथ घुटनों पर रखें", "स्थिर सांस लें, जितना आराम से हो सके रुकें"],
        "precautions_en": "Avoid with knee or ankle injuries.",
        "precautions_hi": "घुटने या टखने की चोट में न करें।",
        "related_conditions": ["stress"],
    },
    {
        "name_en": "Shavasana (Corpse Pose)", "name_hi": "शवासन",
        "image_url": img(1),
        "benefits_en": "Deep relaxation, lowers blood pressure and heart rate, reduces stress and anxiety.",
        "benefits_hi": "गहरी छूट, रक्तचाप और हृदय गति कम करता है, तनाव और चिंता कम करता है।",
        "steps_en": ["Lie flat on your back", "Let arms and legs relax outward", "Close eyes, breathe naturally", "Stay for 5-10 minutes"],
        "steps_hi": ["पीठ के बल सीधे लेटें", "हाथ और पैर बाहर की ओर आराम से छोड़ें", "आंखें बंद करें, स्वाभाविक रूप से सांस लें", "5-10 मिनट रुकें"],
        "precautions_en": "Generally safe for all levels.",
        "precautions_hi": "सभी स्तरों के लिए सुरक्षित।",
        "related_conditions": ["heart", "stress", "hypertension"],
    },
    {
        "name_en": "Anulom Vilom (Alternate Nostril Breathing)", "name_hi": "अनुलोम विलोम",
        "image_url": img(2),
        "benefits_en": "Balances the nervous system, reduces stress, improves lung function and focus.",
        "benefits_hi": "तंत्रिका तंत्र को संतुलित करता है, तनाव कम करता है, फेफड़ों की कार्यक्षमता और एकाग्रता सुधारता है।",
        "steps_en": ["Sit comfortably, spine straight", "Close right nostril, inhale through left", "Close left nostril, exhale through right", "Repeat, alternating sides for 5-10 minutes"],
        "steps_hi": ["आराम से बैठें, रीढ़ सीधी", "दाहिना नथुना बंद करें, बाएं से सांस लें", "बायां नथुना बंद करें, दाहिने से छोड़ें", "5-10 मिनट तक दोहराएं"],
        "precautions_en": "Stop if you feel dizzy; avoid with severe respiratory conditions without guidance.",
        "precautions_hi": "चक्कर आने पर रोकें; गंभीर श्वसन स्थितियों में मार्गदर्शन के बिना न करें।",
        "related_conditions": ["heart", "stress", "hypertension"],
    },
    {
        "name_en": "Kapalbhati (Skull Shining Breath)", "name_hi": "कपालभाति",
        "image_url": img(3),
        "benefits_en": "Detoxifies the body, boosts metabolism, improves digestion and mental alertness.",
        "benefits_hi": "शरीर को detox करता है, चयापचय बढ़ाता है, पाचन और मानसिक सतर्कता सुधारता है।",
        "steps_en": ["Sit with spine straight", "Take a normal inhale", "Exhale forcefully through the nose, pulling navel in", "Repeat 20-30 times per round"],
        "steps_hi": ["रीढ़ सीधी करके बैठें", "सामान्य रूप से सांस लें", "नाक से जोर से सांस छोड़ें, नाभि को अंदर खींचें", "प्रति राउंड 20-30 बार दोहराएं"],
        "precautions_en": "Avoid during pregnancy, with high blood pressure, or hernia.",
        "precautions_hi": "गर्भावस्था, उच्च रक्तचाप, या हर्निया में न करें।",
        "related_conditions": ["diabetes"],
    },
    {
        "name_en": "Parvatasana (Mountain Pose Variation)", "name_hi": "पर्वतासन",
        "image_url": img(4),
        "benefits_en": "Stretches shoulders and spine, improves blood flow to the brain, relieves fatigue.",
        "benefits_hi": "कंधे और रीढ़ को खींचता है, मस्तिष्क में रक्त प्रवाह सुधारता है, थकान दूर करता है।",
        "steps_en": ["Sit in Padmasana or cross-legged", "Raise arms overhead, interlace fingers", "Stretch upward, lengthen spine", "Hold for 15-30 seconds"],
        "steps_hi": ["पद्मासन या पालथी में बैठें", "हाथ ऊपर उठाएं, उंगलियां आपस में मिलाएं", "ऊपर की ओर खिंचाव करें, रीढ़ लंबी करें", "15-30 सेकंड रुकें"],
        "precautions_en": "Avoid with shoulder injury.",
        "precautions_hi": "कंधे की चोट में न करें।",
        "related_conditions": ["stress"],
    },
]

videos = [
    {
        "condition": "heart",
        "title_en": "15-Minute Heart-Healthy Yoga Flow",
        "title_hi": "15 मिनट हृदय-स्वस्थ योग",
        "youtube_url": "https://www.youtube.com/watch?v=q5vfIqveOQU",
        "difficulty_level": "beginner",
        "duration_min": 10,
    },
    {
        "condition": "stress",
        "title_en": "Yoga for Stress & Anxiety Relief",
        "title_hi": "तनाव और चिंता के लिए योग",
        "youtube_url": "https://www.youtube.com/watch?v=hJbRpHZr_d0",
        "difficulty_level": "beginner",
        "duration_min": 20,
    },
    {
        "condition": "diabetes",
        "title_en": "Yoga for Blood Sugar Management",
        "title_hi": "रक्त शर्करा प्रबंधन के लिए योग",
        "youtube_url": "https://www.youtube.com/watch?v=T9vQlk2QVU4",
        "difficulty_level": "beginner",
        "duration_min": 25,
    },
    {
        "condition": "hypertension",
        "title_en": "Yoga for Healthy Blood Pressure",
        "title_hi": "स्वस्थ रक्तचाप के लिए योग",
        "youtube_url": "https://www.youtube.com/watch?v=kUVVgiDR1FE",
        "difficulty_level": "beginner",
        "duration_min": 20,
    },
    {
        "condition": "back_pain",
        "title_en": "Yoga for Back Pain - 20 Minute Stretch & Flexibility",
        "title_hi": "पीठ दर्द के लिए योग - 20 मिनट स्ट्रेच",
        "youtube_url": "https://www.youtube.com/watch?v=cOjFCrd2rYM",
        "difficulty_level": "beginner",
        "duration_min": 20,
    },
    {
        "condition": "back_pain",
        "title_en": "Yoga For Lower Back Pain (Yoga With Adriene)",
        "title_hi": "पीठ के निचले हिस्से के दर्द के लिए योग",
        "youtube_url": "https://www.youtube.com/watch?v=XeXz8fIZDCE",
        "difficulty_level": "beginner",
        "duration_min": 20,
    },
    {
        "condition": "stress",
        "title_en": "Back Pain Relief Stretches - 10 Min Relaxation & Recovery",
        "title_hi": "पीठ दर्द राहत स्ट्रेच - 10 मिनट",
        "youtube_url": "https://www.youtube.com/watch?v=2eA2Koq6pTI",
        "difficulty_level": "beginner",
        "duration_min": 10,
    },
    {
        "condition": "balance",
        "title_en": "30 Min Morning Yoga for Beginners - Calm & Gentle",
        "title_hi": "30 मिनट सुबह का योग - शांत और सौम्य",
        "youtube_url": "https://www.youtube.com/watch?v=8aamtgabSP0",
        "difficulty_level": "beginner",
        "duration_min": 30,
    },
    {
        "condition": "balance",
        "title_en": "10 Minute Morning Yoga for Beginners",
        "title_hi": "10 मिनट सुबह का योग शुरुआती के लिए",
        "youtube_url": "https://www.youtube.com/watch?v=VaoV1PrYft4",
        "difficulty_level": "beginner",
        "duration_min": 10,
    },
    {
        "condition": "diabetes",
        "title_en": "15 Min Morning Yoga - Weight Loss Edition",
        "title_hi": "15 मिनट सुबह का योग - वजन घटाने के लिए",
        "youtube_url": "https://www.youtube.com/watch?v=m756Gz8de4M",
        "difficulty_level": "beginner",
        "duration_min": 15,
    },
    {
        "condition": "stress",
        "title_en": "Yoga for Beginners in Hindi - Part 1",
        "title_hi": "पूर्ण शुरुआती के लिए योग भाग-1",
        "youtube_url": "https://www.youtube.com/watch?v=7cblJJjUkDE",
        "difficulty_level": "beginner",
        "duration_min": 15,
    },
    {
        "condition": "balance",
        "title_en": "Yoga for Beginners - 30 Min Guided Flow (Hindi), Day 1",
        "title_hi": "शुरुआती के लिए योग - 30 मिनट गाइडेड फ्लो, दिन 1",
        "youtube_url": "https://www.youtube.com/watch?v=FdyhENXyIQ4",
        "difficulty_level": "beginner",
        "duration_min": 30,
    },
]

# Clear existing sample data first so re-running this script doesn't duplicate entries
poses_collection.delete_many({})
videos_collection.delete_many({})

poses_collection.insert_many(poses)
videos_collection.insert_many(videos)

print(f"Seeded {len(poses)} poses and {len(videos)} videos.")